#!/bin/python

sources   = "./src/main/js"
resources = "./src/main/resources/js/"
target    = "batch.js"

import os
import os.path

chunks = []
for dirpath, dirnames, filenames in os.walk(sources):
    for filename in sorted(filenames):
        if filename == target or filename.endswith(".loader.js"):
            continue

        print("adding %s" % filename)
        with open(os.path.join(dirpath, filename)) as file:
            chunks.append(file.read())

prepend = "(function ($) {\n"
append  = "\n}(AJS.$));"

destination = os.path.join(resources, target)
with open(destination, "w") as file:
    file.write(prepend)
    file.write("\n".join(chunks))
    file.write(append)

print("saved to %s" % destination)
