#!/bin/bash

set -euo pipefail

URI="${URI:-http://admin:admin@localhost:7990}"

bitbucket-external-hook -b "$URI" -p man set \
    com.ngs.stash.externalhooks.external-hooks:external-pre-receive-hook \
    -e examples/pre-receive-fail -s 123

bitbucket-external-hook -b "$URI" -p man enable \
    com.ngs.stash.externalhooks.external-hooks:external-pre-receive-hook
