#!/bin/bash

echo $(basename $0)

args=("${@}")

echo "arguments passed: ${#args[@]}"
for (( i=0; i<${#args[@]}; i++ )); do
    echo "argument #${i}: ${args[$i]}"
done

date >> /tmp/merge-check-fail-date
env > /tmp/merge-check-fail-env
cat > /tmp/merge-check-fail-stdin

echo "exiting with exitcode 2"
exit 2
